spring:
  application:
    name: fc-board
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #local mysql docker command
    #docker run --name fc-board-mysql -e MYSQL_ROOT_PASSWORD=123123 -p 3306:3306 -d mysql:8.0.32
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
